version: 0.1.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2017
  - macos

platform:
  - x64

for:
  -
    matrix:
      only: 
        - image: Visual Studio 2017
    
    init: 
      - git config --global core.autocrlf input
    
    install: 
      - ps: Install-Product node 10 x64
      - git reset --hard HEAD
      - yarn
      - node --version

    build_script:
      - yarn build
    
    artifacts:
      - path: build/*
        name: Windows

    deploy:
      release: flextag-v$(APPVEYOR_BUILD_VERSION)
      description: 'FlexTag Build $(APPVEYOR_BUILD_VERSION)'
      provider: GitHub
      auth_token:
        secure: BbGNzStA8hQ8cksKOZAgmEduEa8Zr/eKyrlFkupRV3B+HULYvHPhZtozy1heOxAM
      artifact: /.*\.exe/
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true

  -
    matrix:
      only: 
        - image: macos
    cache:
      - node_modules
      - '%APPDATA%\npm-cache'
      - '%USERPROFILE%\.electron'
      - '%USERPROFILE%\AppData\Local\Yarn\cache'

    init:
      - git config --global core.autocrlf input

    install:
      - git reset --hard HEAD
      - npm i yarn -g
      - yarn
      - node --version

    build_script:
      - yarn build
    
    artifacts:
      - path: build/*
        name: MacOS

    deploy:
      release: flextag-v$(APPVEYOR_BUILD_VERSION)
      description: 'FlexTag Build $(APPVEYOR_BUILD_VERSION)'
      provider: GitHub
      auth_token:
        secure: BbGNzStA8hQ8cksKOZAgmEduEa8Zr/eKyrlFkupRV3B+HULYvHPhZtozy1heOxAM
      artifact: /.*\.pkg/
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true

test: off
