module.exports = {
    dictionary: {
        AENC: 'Audio encryption',
        ASPI: 'Audio seek point index',
        APIC: 'Attached picture',
        COMM: 'Comments',
        COMR: 'Commercial frame',
        ENCR: 'Encryption method registration',
        EQUA: 'Equalization',
        EQU2: 'Equalization',
        ETCO: 'Event timing codes',
        GEOB: 'General encapsulated object',
        GRID: 'Group identification registration',
        LINK: 'Linked information',
        MCDI: 'Music CD identifier',
        MLLT: 'MPEG location lookup table',
        OWNE: 'Ownership frame',
        PRIV: 'Private frame',
        PCNT: 'Play counter',
        POPM: 'Popularimeter',
        POSS: 'Position synchronisation frame',
        RBUF: 'Recommended buffer size',
        RVAD: 'Relative volume adjustment',
        RVA2: 'Relative volume adjustment',
        RVRB: 'Reverb',
        SEEK: 'Seek frame',
        SIGN: 'Signature frame',
        SYLT: 'Synchronized lyric/text',
        SYTC: 'Synchronized tempo codes',
        TBPM: 'Beats per minute (BPM)',
        TKEY: 'Musical keyInitial key',
        TCON: 'Content type',
        TMOO: 'Mood',
        TCOP: 'Copyright message',
        TDAT: 'Date',
        TDRC: 'Date',
        TRDA: 'Recording dates',
        TDRC: 'Recording dates',
        TDRC: 'Recording time',
        TIME: 'Time',
        TDRC: 'Time',
        TYER: 'Year',
        TDRC: 'Year',
        TDRL: 'Release time',
        TDTG: 'Tagging time',
        TDEN: 'Encoding time',
        TENC: 'Encoded by',
        TSSE: 'Software/Hardware and settings used for encoding',
        TDLY: 'Playlist delay',
        TIT1: 'Content group description',
        TIT2: 'Title/songname/content description',
        TIT3: 'Subtitle/Description refinement',
        TALB: 'Album/Movie/Show title',
        TLAN: 'Language(s)',
        TLEN: 'Length',
        TSIZ: 'Size',
        TFLT: 'File type',
        TMED: 'Media type',
        TOWN: 'File owner/licensee',
        TPE1: 'Lead performer(s)/Soloist(s)',
        TPE2: 'Band/orchestra/accompaniment',
        TPE3: 'Conductor/performer refinement',
        TPE4: 'Interpreted, remixed, or otherwise modified by',
        TCOM: 'Composer',
        TEXT: 'Lyricist/Text writer',
        IPLS: 'Involved people list',
        TIPL: 'Involved people list',
        TMCL: 'Musician credits list',
        TOAL: 'Original album/movie/show title',
        TOFN: 'Original filename',
        TOLY: 'Original lyricist(s)/text writer(s)',
        TOPE: 'Original artist(s)/performer(s)',
        TORY: 'Original release year',
        TDOR: 'Original release year',
        TRCK: 'Track number/Position in set',
        TPOS: 'Part of a set',
        TSST: 'Set subtitle',
        TPRO: 'Produced notice',
        TPUB: 'Publisher',
        TRSN: 'Internet radio station name',
        TRSO: 'Internet radio station owner',
        TSOA: 'Album sort order',
        TSOP: 'Performer sort order',
        TSOT: 'Title sort order',
        TSRC: 'International Standard Recording Code (ISRC)',
        TXXX: 'User defined text information frame',
        UFID: 'Unique file identifier',
        USER: 'Terms of use',
        USLT: 'Unsynchronized lyric/text transcription',
        WCOM: 'Commercial information',
        WCOP: 'Copyright/Legal information',
        WOAF: 'Official audio file webpage',
        WOAR: 'Official artist/performer webpage',
        WOAS: 'Official audio source webpage',
        WORS: 'Official internet radio station homepage',
        WPAY: 'Payment',
        WPUB: 'Publishers official webpage',
        WXXX: 'User defined URL link frame'
    }
}
